const assert = require('assert/strict')
const { positiveId, milestoneInput, decorateSpecs, filterSpecs, roadmap: projectRoadmap } = require('./roadmap')
const { roadmapPage } = require('./roadmap-ui')
const { canApprove } = require('./server')
const roadmap = (specs, state, data, now) => projectRoadmap(specs, state, data, now, canApprove)
const spec = (id, deps = [], extra = {}) => ({ id, title: id, namespace: 'o/r', url: `http://editor/${id}`, statusIdx: 3, comments: 0, suggestions: 0, required: 0, approvals: 0, dependsOn: deps.map(noteId => ({ noteId })), ...extra })
const ms = { id: '1', namespace: 'o/r', title: 'First', description: '', state: 'open', dueDate: '2026-09-01', version: 1 }
const assignment = (noteId, extra = {}) => ({ noteId, namespace: 'o/r', milestoneId: '1', version: 2, implementers: [], ...extra })
const data = { milestones: [ms], assignments: ['a', 'b', 'c', 'd', 'e', 'f'].map(id => assignment(id)) }
const specs = [spec('a'), spec('b', ['a']), spec('c', ['b']), spec('d', ['e']), spec('e', ['d']), spec('f', ['e']), spec('g', ['missing']), spec('draft', [], { statusIdx: 0 })]
const model = roadmap(specs, new Map(), data, new Date('2026-09-18'))
const node = id => model.nodes.find(n => n.id === id)
assert.equal(node('a').ready, true)
assert.equal(node('draft').ready, false)
assert.equal(node('draft').wave, 0)
assert.equal(node('b').wave, 1)
assert.equal(node('c').wave, 2)
assert.equal(node('d').cycle, true)
assert.equal(node('e').cycle, true)
assert.equal(node('f').cycle, false)
assert.equal(node('f').wave, null)
assert.match(node('f').blockers.join(), /cycle/)
assert.equal(node('g').wave, null)
assert.deepEqual(node('g').dependencies, [{ id: null, title: 'Unresolved prerequisite', state: 'unresolved' }])
assert.equal(model.milestones[0].overdue, true)
assert.equal(model.milestones[0].total, 6)
assert.equal(model.milestones[0].percent, 0)
const implemented = roadmap(specs, new Map([['a', { implemented_at: 'now' }]]), data)
assert.equal(implemented.nodes.find(n => n.id === 'b').ready, true)
assert.equal(implemented.milestones[0].implemented, 1)
for (const change of [specs.slice(1), specs.map(s => s.id === 'a' ? { ...s, namespace: 'other/r' } : s), specs.map(s => s.id === 'a' ? { ...s, topLevel: true } : s)]) {
  const m = roadmap(change, new Map(), data)
  assert.equal(m.milestones[0].incomplete, true)
  assert.equal(m.milestones[0].percent, null)
}
const retired = roadmap(specs, new Map([['a', { superseded_at: 'now', implemented_at: 'now' }]]), data)
assert.equal(retired.milestones[0].implemented, 0)
assert.equal(retired.nodes.find(n => n.id === 'b').wave, null)
const ext = roadmap([spec('a', [], { namespace: 'other/r' }), spec('b', ['a'])], new Map(), { milestones: [ms], assignments: [assignment('b')] })
assert.equal(ext.nodes.find(n => n.id === 'b').dependencies[0].namespace, 'other/r')
assert.equal(ext.nodes.find(n => n.id === 'b').wave, 1)
const numbered = roadmap([spec('a'), spec('b', [], { dependsOn: [{ ns: 'o/r', n: 12 }] })], new Map([['a', { namespace: 'o/r', pr_number: 12 }]]), data)
assert.equal(numbered.nodes.find(n => n.id === 'b').dependencies[0].id, 'a')
assert.equal(roadmap([spec('a', ['a'])], new Map(), data).nodes[0].cycle, true)
assert.equal(roadmap([], new Map(), { milestones: [ms], assignments: [] }).milestones[0].percent, null)
assert.equal(milestoneInput({ title: 'Test', dueDate: '2028-02-29' }).dueDate, '2028-02-29')
for (const dueDate of ['2026-02-29', '2026-04-31', '0000-01-01', '2026-1-1', 'x']) assert.throws(() => milestoneInput({ title: 'Test', dueDate }), /date/)
assert.throws(() => milestoneInput({ title: ' ' }))
assert.equal(positiveId('9223372036854775807'), true)
assert.equal(positiveId('9223372036854775808'), false)
assert.throws(() => milestoneInput({ title: 'a', checkpointTag: 'refs/tags/other' }))
const people = { milestones: [ms], assignments: [assignment('a', { implementers: [{ id: 'u1', login: 'alice' }] }), assignment('b', { milestoneId: null })] }
const decorated = decorateSpecs(specs, people)
assert.equal(filterSpecs(decorated, { implementer: 'me' }, { uid: 'u1' })[0].id, 'a')
assert.equal(filterSpecs(decorated, { implementer: 'none' }).some(s => s.id === 'a'), false)
assert.equal(filterSpecs(decorated, { milestone: 'none' }).some(s => s.id === 'b'), true)
assert.equal(filterSpecs(decorated, { milestone: '1' }).length, 1)
const bad = roadmap([spec('evil', [], { title: '<img src=x onerror=alert(1)>' })], new Map(), { milestones: [], assignments: [] })
const html = roadmapPage({ model: bad, namespaces: ['o/r'], namespace: 'o/r', manageable: [], users: [], specId: 'evil' })
assert.ok(!html.includes('<img src=x'))
assert.ok(html.includes('&lt;img'))
const long = Array.from({ length: 5000 }, (_, i) => spec(`n${i}`, i ? [`n${i - 1}`] : []))
assert.equal(roadmap(long, new Map(), { milestones: [], assignments: [] }).nodes.find(n => n.id === 'n4999').wave, 4999)
for (const extra of [{ required: 1, approvals: 0 }, { comments: 1 }, { suggestions: 1 }, { rolesUnknown: true }]) {
  const result = roadmap([spec('approval', [], extra), spec('after', ['approval'])], new Map(), { milestones: [], assignments: [] })
  assert.equal(result.nodes.find(n => n.id === 'approval').ready, false)
  assert.ok(result.nodes.find(n => n.id === 'approval').blockers.includes('Approval requirements are not met'))
  assert.equal(result.nodes.find(n => n.id === 'after').wave, 1)
}
assert.equal(projectRoadmap([spec('no-gate')], new Map(), { milestones: [], assignments: [] }).nodes[0].ready, false)
const retiredMember = roadmap([spec('retired')], new Map([['retired', { superseded_at: 'now' }]]), {
  milestones: [ms], assignments: [assignment('retired', { implementers: [{ id: 'u1', login: 'alice' }] })]
})
const retiredHtml = roadmapPage({ model: retiredMember, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], specId: 'retired', csrf: 'test' })
assert.ok(retiredHtml.includes('Remove from milestone'))
assert.ok(retiredHtml.includes('Remove implementer'))
assert.ok(!retiredHtml.includes('Find an implementer'))
assert.ok(!retiredHtml.includes('Add implementer'))
const withTop = roadmap([spec('constraint', [], { topLevel: true }), spec('feature', ['constraint'])], new Map(), { milestones: [], assignments: [] })
const topHtml = roadmapPage({ model: withTop, namespaces: ['o/r'], namespace: 'o/r', manageable: [], specId: 'feature' })
assert.ok(topHtml.includes('href="http://editor/constraint"'))
assert.ok(!topHtml.includes('spec=constraint'))
const crowded = roadmap(Array.from({ length: 105 }, (_, i) => spec('s' + i)), new Map(), {
  milestones: Array.from({ length: 105 }, (_, i) => ({ ...ms, id: String(i + 1), title: 'Milestone ' + String(i).padStart(3, '0') })), assignments: []
})
const crowdedHtml = roadmapPage({ model: crowded, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
assert.equal((crowdedHtml.match(/class="milestone"/g) || []).length, 100)
assert.equal((crowdedHtml.match(/Add to milestone/g) || []).length, 0)
assert.ok(crowdedHtml.includes('More milestones'))
assert.ok(Buffer.byteLength(crowdedHtml) < 250000)
const detailHtml = roadmapPage({ model: crowded, namespaces: ['o/r'], namespace: 'o/r', milestoneId: '1', manageable: ['o/r'], csrf: 'test' })
assert.equal((detailHtml.match(/Add to milestone/g) || []).length, 100)
assert.ok(detailHtml.includes('Browse all unassigned specs'))
const multiHtml = roadmapPage({ model: crowded, namespaces: ['o/r', 'o/other'], namespace: 'o/other', manageable: ['o/r', 'o/other'], csrf: 'test' })
assert.equal((multiHtml.match(/Create milestone/g) || []).length, 1)
assert.ok(multiHtml.includes('<option value="o/other" selected>'))

console.log('roadmap unit tests passed')
