const assert = require('assert/strict')
const { positiveId, milestoneInput, decorateSpecs, filterSpecs, roadmap: projectRoadmap } = require('./roadmap')
const { roadmapPage } = require('./roadmap-ui')
const { canApprove } = require('./server')
const roadmap = (specs, state, data, now) => projectRoadmap(specs, state, data, now, canApprove)
const spec = (id, deps = [], extra = {}) => ({ id, title: id, namespace: 'o/r', url: `http://editor/${id}`, statusIdx: 3, comments: 0, suggestions: 0, required: 0, approvals: 0, dependsOn: deps.map(noteId => ({ noteId })), ...extra })
const ms = { id: '1', namespace: 'o/r', title: 'First', description: '', state: 'open', dueDate: '2026-09-01', version: 1 }
const assignment = (noteId, extra = {}) => ({ noteId, namespace: 'o/r', milestoneId: '1', version: 2, implementers: [], ...extra })
const data = { milestones: [ms], assignments: ['a', 'b', 'c', 'd', 'e', 'f'].map(id => assignment(id)) }
const specs = [spec('a'), spec('b', ['a']), spec('c', ['b']), spec('d', ['e']), spec('e', ['d']), spec('f', ['e']), spec('g', ['missing']), spec('draft', [], { statusIdx: 0 })]
const model = roadmap(specs, new Map(), data, new Date('2026-09-18'))
const node = id => model.nodes.find(n => n.id === id)
assert.equal(node('a').ready, true)
assert.equal(node('draft').ready, false)
assert.equal(node('draft').wave, 0)
assert.equal(node('b').wave, 1)
assert.equal(node('c').wave, 2)
assert.equal(node('d').cycle, true)
assert.equal(node('e').cycle, true)
assert.equal(node('f').cycle, false)
assert.equal(node('f').wave, null)
assert.match(node('f').blockers.join(), /cycle/)
assert.equal(node('g').wave, null)
assert.deepEqual(node('g').dependencies, [{ id: null, title: 'Unresolved prerequisite', state: 'unresolved' }])
assert.equal(model.milestones[0].overdue, true)
assert.equal(model.milestones[0].total, 6)
assert.equal(model.milestones[0].percent, 0)
const implemented = roadmap(specs, new Map([['a', { implemented_at: 'now' }]]), data)
assert.equal(implemented.nodes.find(n => n.id === 'b').ready, true)
assert.equal(implemented.milestones[0].implemented, 1)
for (const change of [specs.slice(1), specs.map(s => s.id === 'a' ? { ...s, namespace: 'other/r' } : s), specs.map(s => s.id === 'a' ? { ...s, topLevel: true } : s)]) {
  const m = roadmap(change, new Map(), data)
  assert.equal(m.milestones[0].incomplete, true)
  assert.equal(m.milestones[0].percent, null)
}
const retired = roadmap(specs, new Map([['a', { superseded_at: 'now', implemented_at: 'now' }]]), data)
assert.equal(retired.milestones[0].implemented, 0)
assert.equal(retired.nodes.find(n => n.id === 'b').wave, null)
const ext = roadmap([spec('a', [], { namespace: 'other/r' }), spec('b', ['a'])], new Map(), { milestones: [ms], assignments: [assignment('b')] })
assert.equal(ext.nodes.find(n => n.id === 'b').dependencies[0].namespace, 'other/r')
assert.equal(ext.nodes.find(n => n.id === 'b').wave, 1)
const numbered = roadmap([spec('a'), spec('b', [], { dependsOn: [{ ns: 'o/r', n: 12 }] })], new Map([['a', { namespace: 'o/r', pr_number: 12 }]]), data)
assert.equal(numbered.nodes.find(n => n.id === 'b').dependencies[0].id, 'a')
assert.equal(roadmap([spec('a', ['a'])], new Map(), data).nodes[0].cycle, true)
assert.equal(roadmap([], new Map(), { milestones: [ms], assignments: [] }).milestones[0].percent, null)
assert.equal(milestoneInput({ title: 'Test', dueDate: '2028-02-29' }).dueDate, '2028-02-29')
for (const dueDate of ['2026-02-29', '2026-04-31', '0000-01-01', '2026-1-1', 'x']) assert.throws(() => milestoneInput({ title: 'Test', dueDate }), /date/)
assert.throws(() => milestoneInput({ title: ' ' }))
assert.equal(positiveId('9223372036854775807'), true)
assert.equal(positiveId('9223372036854775808'), false)
assert.throws(() => milestoneInput({ title: 'a', checkpointTag: 'refs/tags/other' }))
const people = { milestones: [ms], assignments: [assignment('a', { implementers: [{ id: 'u1', login: 'alice' }] }), assignment('b', { milestoneId: null })] }
const decorated = decorateSpecs(specs, people)
assert.equal(filterSpecs(decorated, { implementer: 'me' }, { uid: 'u1' })[0].id, 'a')
assert.equal(filterSpecs(decorated, { implementer: 'none' }).some(s => s.id === 'a'), false)
assert.equal(filterSpecs(decorated, { milestone: 'none' }).some(s => s.id === 'b'), true)
assert.equal(filterSpecs(decorated, { milestone: '1' }).length, 1)
const bad = roadmap([spec('evil', [], { title: '<img src=x onerror=alert(1)>' })], new Map(), { milestones: [], assignments: [] })
const html = roadmapPage({ model: bad, namespaces: ['o/r'], namespace: 'o/r', manageable: [], users: [], specId: 'evil' })
assert.ok(!html.includes('<img src=x'))
assert.ok(html.includes('&lt;img'))
const long = Array.from({ length: 5000 }, (_, i) => spec(`n${i}`, i ? [`n${i - 1}`] : []))
assert.equal(roadmap(long, new Map(), { milestones: [], assignments: [] }).nodes.find(n => n.id === 'n4999').wave, 4999)
for (const extra of [{ required: 1, approvals: 0 }, { comments: 1 }, { suggestions: 1 }, { rolesUnknown: true }]) {
  const result = roadmap([spec('approval', [], extra), spec('after', ['approval'])], new Map(), { milestones: [], assignments: [] })
  assert.equal(result.nodes.find(n => n.id === 'approval').ready, false)
  assert.ok(result.nodes.find(n => n.id === 'approval').blockers.includes('Approval requirements are not met'))
  assert.equal(result.nodes.find(n => n.id === 'after').wave, 1)
}
assert.equal(projectRoadmap([spec('no-gate')], new Map(), { milestones: [], assignments: [] }).nodes[0].ready, false)
const retiredMember = roadmap([spec('retired')], new Map([['retired', { superseded_at: 'now' }]]), {
  milestones: [ms], assignments: [assignment('retired', { implementers: [{ id: 'u1', login: 'alice' }] })]
})
const retiredHtml = roadmapPage({ model: retiredMember, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], specId: 'retired', csrf: 'test' })
assert.ok(retiredHtml.includes('Remove from milestone'))
assert.ok(retiredHtml.includes('Specs in this milestone'), 'a short list view carries the spec list in every edit form')
assert.ok(retiredHtml.includes('value="retired:'))
assert.ok(retiredHtml.includes('Remove implementer'))
assert.ok(!retiredHtml.includes('Find an implementer'))
assert.ok(!retiredHtml.includes('Add implementer'))
const withTop = roadmap([spec('constraint', [], { topLevel: true }), spec('feature', ['constraint'])], new Map(), { milestones: [], assignments: [] })
const topHtml = roadmapPage({ model: withTop, namespaces: ['o/r'], namespace: 'o/r', manageable: [], specId: 'feature' })
assert.ok(topHtml.includes('href="http://editor/constraint"'))
assert.ok(!topHtml.includes('spec=constraint'))
const crowded = roadmap(Array.from({ length: 105 }, (_, i) => spec('s' + i)), new Map(), {
  milestones: Array.from({ length: 105 }, (_, i) => ({ ...ms, id: String(i + 1), title: 'Milestone ' + String(i).padStart(3, '0') })), assignments: []
})
const crowdedHtml = roadmapPage({ model: crowded, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
assert.equal((crowdedHtml.match(/class="milestone"/g) || []).length, 100)
assert.equal((crowdedHtml.match(/<article class="milestone" id="milestone-\d+">/g) || []).length, 100, 'every card is a fragment target')
assert.equal((crowdedHtml.match(/name="spec"/g) || []).length, 0)
assert.equal((crowdedHtml.match(/Add specs on the milestone/g) || []).length, 100, 'a long list view points at each milestone page instead')
assert.ok(crowdedHtml.includes('More milestones'))
assert.ok(Buffer.byteLength(crowdedHtml) < 250000)
const detailHtml = roadmapPage({ model: crowded, namespaces: ['o/r'], namespace: 'o/r', milestoneId: '1', manageable: ['o/r'], csrf: 'test' })
assert.equal((detailHtml.match(/name="spec"/g) || []).length, 100)
assert.ok(detailHtml.includes('Showing 100 of 105 specs.'))
assert.ok(detailHtml.includes('href="/?ns=o%2Fr"'))
assert.ok(detailHtml.includes('Specs in this milestone'))
assert.equal((detailHtml.match(/value="delete-milestone"/g) || []).length, 1)
assert.equal((crowdedHtml.match(/value="delete-milestone"/g) || []).length, 100)
assert.ok(detailHtml.includes('value="s0:0"'))
const multiHtml = roadmapPage({ model: crowded, namespaces: ['o/r', 'o/other'], namespace: 'o/other', manageable: ['o/r', 'o/other'], csrf: 'test' })
assert.equal((multiHtml.match(/Create milestone/g) || []).length, 1)
assert.ok(multiHtml.includes('<option value="o/other" selected>'))

const ms2 = { ...ms, id: '2', title: 'Second', dueDate: '' }
const rosterModel = roadmap([spec('ready'), spec('gated', [], { required: 1, approvals: 0 })], new Map(),
  { milestones: [ms], assignments: [assignment('ready'), assignment('gated', { implementers: [{ id: 'u1', login: 'alice' }] })] })
const rosterHtml = roadmapPage({ model: rosterModel, namespaces: ['o/r'], namespace: 'o/r', manageable: [] })
assert.ok(rosterHtml.includes('class="members"'))
assert.ok(rosterHtml.includes('>ready</a>') && rosterHtml.includes('>gated</a>'))
assert.ok(!rosterHtml.includes('<form method="post"'), 'a viewer who cannot manage gets the roster and no forms')
assert.ok(rosterHtml.includes('Ready to implement'))
assert.ok(rosterHtml.includes('Approval requirements are not met'))
assert.ok(rosterHtml.includes('@alice'))
assert.ok(rosterHtml.includes('spec=gated'))
assert.ok(rosterHtml.includes('<a href="http://editor/gated" target="_blank" rel="noopener">'), 'the roster opens a spec the way the board does')
assert.ok(rosterHtml.includes('href="/?milestone=1"'))
const twoMilestones = roadmap([spec('own'), spec('other')], new Map(),
  { milestones: [ms, ms2], assignments: [assignment('own'), assignment('other', { milestoneId: '2' })] })
const twoHtml = roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
for (const id of ['1', '2']) assert.ok(twoHtml.includes(`href="/?milestone=${id}"`))
const firstCard = twoHtml.split('id="milestone-1"')[1].split('id="milestone-2"')[0]
const firstFieldset = firstCard.split('<fieldset>')[1].split('</fieldset>')[0]
const firstHeld = firstFieldset.split('<details>')[1]
assert.ok(firstHeld.includes('Held by other milestones (1)'))
assert.ok(firstHeld.includes('value="other:2" aria-label="other (in Second)">'), 'a spec held elsewhere is offered unticked, with its milestone named')
assert.ok(firstHeld.includes('(in Second)</span>'))
assert.ok(firstFieldset.split('<details>')[0].includes('value="own:2" checked'))
assert.ok(!firstFieldset.includes('Showing '), 'a list that fits says nothing about what it is showing')
assert.ok(firstFieldset.includes('Ticking a spec held by another milestone moves it here.'))
assert.equal((firstCard.match(/name="member"/g) || []).length, 1, 'only this milestone\'s own members can be removed by a save')
const closedPick = roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], specId: 'own', csrf: 'test' })
assert.ok(closedPick.includes('<option value="2"'), 'the spec panel lists every milestone in the namespace')
const readOnly = roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: [], specId: 'own' })
assert.ok(readOnly.includes('Only project approvers and board admins can change this'))
assert.ok(readOnly.includes('Milestone: First'))
const movedNotice = roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: [], saved: 'members', savedCounts: { added: 2, moved: 1, removed: 1 } })
assert.ok(movedNotice.includes('Milestone saved. Added 2 (1 moved from another milestone), removed 1.'))
for (const [saved, text] of [['members', 'Milestone saved. Added 2, removed 1.'], ['milestone-deleted', 'Milestone deleted. Its specs are now unassigned.'], ['detached', 'Removed from planning.']]) {
  const notice = roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: [], saved, savedCounts: { added: 2, removed: 1 } })
  assert.ok(notice.includes('<p class="notice" role="status">'))
  assert.ok(notice.includes(text))
}
assert.ok(!roadmapPage({ model: twoMilestones, namespaces: ['o/r'], namespace: 'o/r', manageable: [], saved: 'nonsense' }).includes('role="status"'))

const pairModel = roadmap([spec('alpha'), spec('beta')], new Map(),
  { milestones: [ms], assignments: [assignment('alpha', { implementers: [{ id: 'u1', login: 'alice' }] }), assignment('beta')] })
const pairHtml = roadmapPage({ model: pairModel, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
const pairFieldset = pairHtml.split('class="edit">')[1].split('<fieldset>')[1].split('</fieldset>')[0]
for (const title of ['alpha', 'beta']) assert.equal(pairFieldset.split(`>${title}</a>`).length - 1, 1, 'the ticking list names each member once')
const alphaRow = pairFieldset.split('<li>').find(row => row.includes('>alpha</a>'))
assert.ok(alphaRow.startsWith('<input type="checkbox" name="spec" value="alpha:2" checked'), 'the checkbox is the row\'s first child')
assert.ok(alphaRow.includes('class="badge">approved') && alphaRow.includes('@alice'), 'the row a manager ticks carries the facts')
assert.ok(pairHtml.includes('href="/roadmap?ns=o%2Fr&spec=alpha#spec-panel"'), 'Details lands on the panel without narrowing a page that lists every milestone')
assert.ok(!pairHtml.includes('&milestone=1&spec='), 'a reader with no milestone filter does not get one from Details')
const pairFiltered = roadmapPage({ model: pairModel, namespaces: ['o/r'], namespace: 'o/r', milestoneId: '1', manageable: ['o/r'], csrf: 'test' })
assert.ok(pairFiltered.includes('href="/roadmap?ns=o%2Fr&milestone=1&spec=alpha#spec-panel"'), 'Details keeps a milestone filter the reader already chose')
assert.ok(pairHtml.includes('<a href="http://editor/alpha" target="_blank" rel="noopener">'))
assert.ok(!pairHtml.includes('Only project approvers and board admins can add or edit milestones'))

const mixed = roadmap([spec('mine'), spec('loose'), spec('elsewhere')], new Map(),
  { milestones: [ms, ms2], assignments: [assignment('mine'), assignment('elsewhere', { milestoneId: '2' })] })
const mixedFieldset = roadmapPage({ model: mixed, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
  .split('id="milestone-1"')[1].split('<fieldset>')[1].split('</fieldset>')[0]
const [mixedRows, mixedHeld] = mixedFieldset.split('<details>')
assert.ok(mixedRows.includes('>mine</a>') && mixedRows.includes('>loose</a>'))
assert.ok(!mixedRows.includes('>elsewhere</a>'))
assert.ok(mixedHeld.includes('Held by other milestones (1)') && mixedHeld.includes('>elsewhere</a>'))

const crowd = roadmap(Array.from({ length: 140 }, (_, i) => spec('q' + i)), new Map(), { milestones: [ms], assignments: [] })
const crowdHtml = roadmapPage({ model: crowd, namespaces: ['o/r'], namespace: 'o/r', manageable: ['o/r'], csrf: 'test' })
assert.ok(crowdHtml.includes('Showing 100 of 140 specs.'))
assert.ok(crowdHtml.includes('href="/?ns=o%2Fr"'))

const panelFrom = roadmapPage({ model: pairModel, namespaces: ['o/r'], namespace: 'o/r', milestoneId: '1', specId: 'alpha', manageable: [] })
assert.ok(panelFrom.includes('<section class="panel" id="spec-panel">'))
assert.ok(panelFrom.includes('#milestone-1">Back to First</a>'))
const panelAlone = roadmapPage({ model: pairModel, namespaces: ['o/r'], namespace: 'o/r', specId: 'alpha', manageable: [] })
assert.ok(panelAlone.includes('>Close<') && !panelAlone.includes('Back to'))
assert.ok(panelAlone.includes('Only project approvers and board admins can add or edit milestones'))

console.log('roadmap unit tests passed')
